### PR TITLE
Marry lisa's repo with source83's

### PR DESCRIPTION
**Pull request by sirkitree**
This would get source83's repo in sync with lisa's.

This is the version we're currently using on VR Sites do to the functionality it provides in regard to logging of users. This info is recorded in a mysql database which is then displayed in the lobby so that you can see who else is online.

I'd like to keep Lisa's version as the official version and keep the official version running on VR Sites if possible so since no one else will champion this change, I will. I'd love a review and any suggestions to make this better.

### CODE REVIEW

**Comment by timschwartz** [comment]
Could this be modified to be a plugin? Maybe store it at /plugins/session-storage/mysql.js

I think the ability to implement this functionality with LDAP or a flat file would be nice.

**Comment by sirkitree** [comment]
I'd love that. I was hoping to get this in in it's current form since we're already using it and then improve upon it. If that takes a while I may work on turning it into a plugin.

Love to hear from @lisa-lionheart on what she thinks her role may be in the project going forward, do you still have interest @lisa-lionheart? Should we go on with a fork at /vrsites/janus-server?

**Comment by lisa-lionheart** [comment]
I think it might be best to set up a JanusVR git-hub team or something and transfer the repo over, this haven't been my project for quiet some time so I'm not sure I can really be an authority on how well it works in practice.

I haven't been active in the community for several months but I still lurk on/r/janusvr and would like to help out again some time when I have the time

**Comment by sirkitree** [comment]
Thanks @lisa-lionheart. I'll send you an invite to the org so you can move this over there.

**Pull request merged**
