### PR TITLE
Added authentication plugin support, with examples for LDAP and MySQL

### PR DESCRIPTION
**Pull request by timschwartz**

### CODE REVIEW

**Comment by sirkitree** [comment]
@timschwartz would you mind providing any testing instructions for the ldap and mysql implementations? Reviewing this now.

**Comment by sirkitree** [comment]
General feedback (keep in mind I don't have commit access, so these are just suggestions, not mandates):

1. Should we keep the configuration options within the config.js file? ldap-config.js and mysql-config.js could then just be ldap.js and mysql.js (or perhaps *-auth.js) and all configuration options can be found in one place.
1. I have some minor issue with the formatting, but I won't be picky until we have some sort of formal linting happening for this project.
1. I don't claim to be a nodejs expert, but I'm not sure that every function being a prototype of `exports` is a good idea. I'd love some other thoughts on this, but the pattern I most typically see is to have a main function (pseudo class) with object (pseudo methods) and then just export that. Just a topic for discussion.
1. Instead of the user having to add 'module.exports.auth = require("./mysql-config.js");' to config.js, perhaps this would be better suited as a variable like `var authMethod = 'mysql';` and then require the appropriate file based on this variable. Thoughts?

Overall, this is some really great work and I'm looking forward to trying this out.

Regarding security, VR Sites currently relies on the [hash](http://php.net/manual/en/function.hash.php) function with the sha512 algorthym and a salt. In what format do you see the client (Janus) sending the username and password to the server? Would we get Janus to do the encryption or would we get it in plain text format and encode ourselves?

I'm not a security expert but it would seem that each server might want to first broadcast to Janus what it's expecting to receive so that plain text passwords are never sent over the wire.

**Comment by timschwartz** [comment]
1. While AUTH_TYPE could and probably should be moved to config.js, the other variables are specific to the libraries they interface with. Like, only LDAP needs a LDAP_BASE set, and only mysql needs a DB set. This leads me to think they should stay with their respective files with the name -config.js so people will realize they need to edit them.

2. Do you mean the places where I forgot to use the weird brace style? ;)
I can fix those.

3. I'm not a nodejs expert either, in fact this was my first experience with it. Could you provide an example of what you're talking about?

4. Do you mean like this?
var authMethod = 'mysql';

module.exports.auth = require("./"+authMethod+"-config.js");

**Comment by sirkitree** [comment]
1 and 4 sort of go hand in hand. It also might be nice to start a plugins directory.

With that in mind, 4 would be something like:
```js
/** 
  Set authMethod if you want to provide authentication with your server. 
  Valid options can be found in the plugins/authentication directory and are
  expressed as a string.
**/
// var authMethod = ''; // uncomment and set. valid options are 'mysql' or 'ldap'
if (authMethod !== 'null' && typeof authMethod !== 'undefined') {
  module.exports.auth = require('./plugins/authentication/' + authMethod + '.js');
}
```

The reason behind number 4 is that users aren't typically expected to write code, just set some options. In our case it might be okay, but just trying to think of how I've seen other projects do similar things.

For number 3, take a look at the [commander](https://github.com/tj/commander.js) module. You'll see there that it creates a [main function](https://github.com/tj/commander.js/blob/master/index.js#L83) (or Class) and then each it extends the Command prototype for each function. This would make these plugins look something like this instead:

```js
function MysqlAuth = function() { ... }
function MysqlAuth.prototype.init = function() { ... }

/** Expose MysqlAuth **/
exports.MysqlAuth = MysqlAuth;
```
The `.prototype` is not required, and I'm not actually sure what the advantage is to using prototype vs straight up functions. This would also be better IMHO:

```js
var MysqlAuth = MysqlAuth || {};

MysqlAuth.init = function() { ... }

MysqlAuth.options = {
        uri: 'ldap://'+LDAP_HOST, // string
        version: 3, // integer, default is 3,
        starttls: false, // boolean, default is false
        connecttimeout: 3, // seconds, default is -1 (infinite timeout), connect timeout
        timeout: 5000, // milliseconds, default is 5000 (infinite timeout is unsupported), operation timeout
        reconnect: true, // boolean, default is true,
        backoffmax: 32 // seconds, default is 32, reconnect timeout
    };

/** Expose MysqlAuth **/
exports.MysqlAuth = MysqlAuth;
```

There are some better explanations here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Introduction_to_Object-Oriented_JavaScript

As for formatting, it's standard courtesy to try to follow the conventions that a project is already using. I think mostly you're doing that. The only thing that really stood out was the extra indentation within `ldap-config.js`.

**Comment by sirkitree** [comment]
The other issue I'm trying to resolve here is that vr sites is currently using source83's version of the server which logs users to a mysql database already. Now the db for logging these may be different from the mysql authentication, but I need to reconcile that fork with lisa's before we decide to pull this in I think since we're kinda dependent upon that change (it's what allows the list of active users in the lobby currently).

**Pull request closed without merging**
